// Mocks generated by Mockito 5.0.14 from annotations
// in ar_indoor_nav_admin/test/data/bldg/bldg_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:ar_indoor_nav_admin/data/bldg_detail/model/bldg_detail.dart'
    as _i3;
import 'package:ar_indoor_nav_admin/data/building/data_provider/building_data_provider.dart'
    as _i2;
import 'package:ar_indoor_nav_admin/data/building/model/building.dart' as _i6;
import 'package:ar_indoor_nav_admin/data/building/repository/building_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeBuildingDataProvider_0 extends _i1.Fake
    implements _i2.BuildingDataProvider {}

class _FakeBldgDetail_1 extends _i1.Fake implements _i3.BldgDetail {}

/// A class which mocks [BuildingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildingRepository extends _i1.Mock
    implements _i4.BuildingRepository {
  MockBuildingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BuildingDataProvider get buildingDataProvider => (super.noSuchMethod(
      Invocation.getter(#buildingDataProvider),
      returnValue: _FakeBuildingDataProvider_0()) as _i2.BuildingDataProvider);
  @override
  _i5.Future<List<_i6.Building>> getAllBuildings() =>
      (super.noSuchMethod(Invocation.method(#getAllBuildings, []),
              returnValue: Future<List<_i6.Building>>.value(<_i6.Building>[]))
          as _i5.Future<List<_i6.Building>>);
  @override
  _i5.Future<_i3.BldgDetail> getBuildingDetails(String? bldgId) =>
      (super.noSuchMethod(Invocation.method(#getBuildingDetails, [bldgId]),
              returnValue: Future<_i3.BldgDetail>.value(_FakeBldgDetail_1()))
          as _i5.Future<_i3.BldgDetail>);
  @override
  String toString() => super.toString();
}
